services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-pass}
      POSTGRES_DB: ${POSTGRES_DB-avito-fall-2025}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER-user} -d ${POSTGRES_DB-avito-fall-2025}" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  migrate:
    image: migrate/migrate:latest
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    networks:
      - app
    command: [
      "-path", "/migrations",
      "-database", "postgres://${POSTGRES_USER-user}:${POSTGRES_PASSWORD-pass}@db:5432/${POSTGRES_DB-avito-fall-2025}?sslmode=disable",
      "up"
    ]
    restart: on-failure

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    environment:
      APP_MODE: ${APP_MODE-dev}

      POSTGRES_USER: ${POSTGRES_USER-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-pass}
      POSTGRES_DB: ${POSTGRES_DB-avito-fall-2025}

      PG_HOST: ${PG_HOST-db}
      PG_USER: ${PG_USER-user}
      PG_PASSWORD: ${PG_PASSWORD-pass}
      PG_DB: ${PG_DB-avito-fall-2025}
      PG_SSLMODE: ${PG_SSLMODE-disable}

      HTTP_READ_TIMEOUT: ${HTTP_READ_TIMEOUT-5s}
      HTTP_WRITE_TIMEOUT: ${HTTP_WRITE_TIMEOUT-5s}
      HTTP_IDLE_TIMEOUT: ${HTTP_IDLE_TIMEOUT-30s}

      JWT_SECRET: ${JWT_SECRET-there-definitely-should-not-be-default-value-but-for-demonstration-simplicity-its-there}

    ports:
      - "8080:8080"
    networks:
      - app
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8080" ]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  db-data:

networks:
  app:
    driver: bridge